"""Interactive flashcard and quiz review from NotebookLM-generated JSON.

Loads flashcard and quiz JSON files generated by the from-obsidian command
and presents them interactively in the terminal.

Flashcard format: {"title": "...", "cards": [{"front": "...", "back": "..."}]}
Quiz format: {"title": "...", "questions": [{"question": "...", "answerOptions": [...]}]}
"""

from __future__ import annotations

import json
import random
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class Flashcard:
    front: str
    back: str
    source: str = ""


@dataclass
class QuizQuestion:
    question: str
    options: list[QuizOption]
    hint: str = ""
    source: str = ""


@dataclass
class QuizOption:
    text: str
    is_correct: bool
    rationale: str = ""


@dataclass
class ReviewResult:
    total: int = 0
    correct: int = 0
    incorrect: int = 0
    skipped: int = 0
    cards_reviewed: list[dict] = field(default_factory=list)

    @property
    def score_pct(self) -> float:
        return (self.correct / self.total * 100) if self.total > 0 else 0.0


def load_flashcards(directory: Path) -> list[Flashcard]:
    """Load all flashcard JSON files from a directory."""
    cards: list[Flashcard] = []
    for path in sorted(directory.glob("*-flashcards.json")):
        try:
            data = json.loads(path.read_text())
            source = data.get("title", path.stem)
            for card in data.get("cards", []):
                cards.append(
                    Flashcard(
                        front=card["front"],
                        back=card["back"],
                        source=source,
                    )
                )
        except (json.JSONDecodeError, KeyError):
            continue
    return cards


def load_quizzes(directory: Path) -> list[QuizQuestion]:
    """Load all quiz JSON files from a directory."""
    questions: list[QuizQuestion] = []
    for path in sorted(directory.glob("*-quiz.json")):
        try:
            data = json.loads(path.read_text())
            source = data.get("title", path.stem)
            for q in data.get("questions", []):
                options = [
                    QuizOption(
                        text=opt["text"],
                        is_correct=opt.get("isCorrect", False),
                        rationale=opt.get("rationale", ""),
                    )
                    for opt in q.get("answerOptions", [])
                ]
                questions.append(
                    QuizQuestion(
                        question=q["question"],
                        options=options,
                        hint=q.get("hint", ""),
                        source=source,
                    )
                )
        except (json.JSONDecodeError, KeyError):
            continue
    return questions


def discover_content(directory: Path) -> tuple[Path | None, Path | None]:
    """Find flashcard and quiz subdirectories within a downloads directory.

    Checks for flashcards/ and quizzes/ subdirectories, or falls back
    to the directory itself if it contains JSON files directly.
    """
    flashcard_dir: Path | None = None
    quiz_dir: Path | None = None

    # Check for subdirectories first
    fc_sub = directory / "flashcards"
    if fc_sub.is_dir() and list(fc_sub.glob("*-flashcards.json")):
        flashcard_dir = fc_sub

    quiz_sub = directory / "quizzes"
    if quiz_sub.is_dir() and list(quiz_sub.glob("*-quiz.json")):
        quiz_dir = quiz_sub

    # Fall back to directory itself
    if not flashcard_dir and list(directory.glob("*-flashcards.json")):
        flashcard_dir = directory
    if not quiz_dir and list(directory.glob("*-quiz.json")):
        quiz_dir = directory

    return flashcard_dir, quiz_dir


def shuffle_items(items: list, enabled: bool = True) -> list:
    """Shuffle a list if enabled, otherwise return as-is."""
    if enabled:
        shuffled = list(items)
        random.shuffle(shuffled)
        return shuffled
    return items
